### ISSUE TITLE
netdisco.NetdiscoWrapper error 

### ISSUE THREAD

**Issue by pejacoby** [noise-lab/iot-inspector-client#22]
Noticed this error in the logs on MacOS 10.13.6 when running the tool today.  It reoccurs once every 30 seconds or so.  The tools seems to run fine and the web interface updates with traffic information.

[2019-05-26 17:52:59.531376] ================================================================================
Time: 2019-05-26 17:52:59.531067
Function: <bound method NetdiscoWrapper._run_netdisco of <netdisco.NetdiscoWrapper object at 0x105c43f90>> [] {}
Exception: list indices must be integers, not str
Traceback (most recent call last):
  File "utils.py", line 223, in safe_run
  File "netdisco.py", line 81, in _run_netdisco
  File "netdisco.py", line 98, in _parse_netdisco_output
TypeError: list indices must be integers, not str

**Comment by crazyideas21** [comment]
Fixed in #38
