### ISSUE TITLE
[Linux]Syntax error

### ISSUE THREAD

**Issue by fnordson** [noise-lab/iot-inspector-client#37]
Hi, 
I have the up to date Kali Linux installation. 
I got the client installed and started it but it won't give me an URL to work with and this is what it looks like:

```
Starting IoT Inspector...
WARNING: No route found for IPv6 destination :: (no default route?)
Traceback (most recent call last):
  File "start_inspector.py", line 2, in <module>
    import inspector
  File "/root/princeton-iot-inspector/iot-inspector-client/v2-src/inspector.py", line 12, in <module>
    from netdisco_wrapper import NetdiscoWrapper
  File "/root/princeton-iot-inspector/iot-inspector-client/v2-src/netdisco_wrapper.py", line 13, in <module>
    from netdisco.discovery import NetworkDiscovery
  File "/usr/local/lib/python2.7/dist-packages/netdisco/discovery.py", line 7, in <module>
    from .mdns import MDNS
  File "/usr/local/lib/python2.7/dist-packages/netdisco/mdns.py", line 2, in <module>
    import zeroconf
  File "/usr/local/lib/python2.7/dist-packages/zeroconf/__init__.py", line 211
    def current_time_millis() -> float:
                              ^
SyntaxError: invalid syntax
Updating software...
Already up to date.
Updating depdencies...
Requirement already satisfied: Flask in /usr/lib/python2.7/dist-packages (1.1.1)
Requirement already satisfied: flask-cors in /usr/local/lib/python2.7/dist-packages (3.0.8)
Requirement already satisfied: Flask>=0.9 in /usr/lib/python2.7/dist-packages (from flask-cors) (1.1.1)
Requirement already satisfied: Six in /usr/lib/python2.7/dist-packages (from flask-cors) (1.13.0)
Requirement already satisfied: requests in /usr/lib/python2.7/dist-packages (2.21.0)
Requirement already satisfied: netaddr in /usr/lib/python2.7/dist-packages (0.7.19)
Requirement already satisfied: scapy-ssl_tls in /usr/local/lib/python2.7/dist-packages (2.0.0)
Requirement already satisfied: pycryptodomex>=3.4 in /usr/lib/python2.7/dist-packages (from scapy-ssl_tls) (3.6.1)
Requirement already satisfied: scapy<2.3.3,>=2.2.0 in /usr/local/lib/python2.7/dist-packages (from scapy-ssl_tls) (2.3.2)
Requirement already satisfied: tinyec>=0.3.1 in /usr/local/lib/python2.7/dist-packages (from scapy-ssl_tls) (0.3.1)
Requirement already satisfied: scapy-http in /usr/local/lib/python2.7/dist-packages (1.8.2)
Requirement already satisfied: scapy in /usr/local/lib/python2.7/dist-packages (from scapy-http) (2.3.2)
Requirement already satisfied: netdisco in /usr/local/lib/python3.7/dist-packages (2.6.0)
Requirement already satisfied: requests>=2.0 in /usr/lib/python3/dist-packages (from netdisco) (2.21.0)
Requirement already satisfied: zeroconf>=0.21.0 in /usr/local/lib/python3.7/dist-packages (from netdisco) (0.24.0)
Requirement already satisfied: ifaddr in /usr/local/lib/python3.7/dist-packages (from zeroconf>=0.21.0->netdisco) (0.1.6)
```

**Comment by crazyideas21** [comment]
The code is Python 3 only. We will update the installation script. #36

**Comment by fnordson** [comment]
I do have python 2 and 3 installed. 
What am I to do now?

**Comment by crazyideas21** [comment]
The installation script is written in Python 2. If you're interested, you could help us port the installation script to Python 3. (We're currently behind some other deadlines and won't get a chance to fix this issue until mid-December.) See #36.

**Comment by fnordson** [comment]
Aaah now I get it. 
I would love to help you out but I'm not really versed enough. Sorry :(
