### ISSUE TITLE
tcpdump package required for rpi version

### ISSUE THREAD

**Issue by ggmartins** [noise-lab/iot-inspector-client#48]
hey there
back to your last comment in #39 "The users are not expected to install any missing packets;"

I removed tcpdump via apt-get purge and this message appears every second:

```
================================================================================
Time: 2020-01-02 20:10:06.080211
Function: <function sniff at 0x75910810> [] {'prn': <bound method PacketProcessor.process_packet of <packet_processor.PacketProcessor object at 0x759807f0>>, 'stop_filter': <function PacketCapture._capture_packets.<locals>.<lambda> at 0x73dea738>, 'filter': 'arp or (host not 192.168.143.23 and ether host b8:27:eb:4e:74:a1) or (port 67 or port 68)', 'timeout': 30}
Exception: tcpdump is not available. Cannot use filter !
Traceback (most recent call last):
  File "/root/princeton-iot-inspector/iot-inspector-client/v2-src/utils.py", line 246, in safe_run
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/scapy/sendrecv.py", line 972, in sniff
    sniffer._run(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/scapy/sendrecv.py", line 842, in _run
    *arg, **karg)] = iface
  File "/usr/local/lib/python3.7/dist-packages/scapy/arch/linux.py", line 475, in __init__
    attach_filter(self.ins, filter, iface)
  File "/usr/local/lib/python3.7/dist-packages/scapy/arch/linux.py", line 160, in attach_filter
    bp = compile_filter(bpf_filter, iface)
  File "/usr/local/lib/python3.7/dist-packages/scapy/arch/common.py", line 165, in compile_filter
    raise Scapy_Exception("tcpdump is not available. Cannot use filter !")
scapy.error.Scapy_Exception: tcpdump is not available. Cannot use filter !
```
It works with tcpdump installed, so it's not really a bug imho.

**Comment by crazyideas21** [comment]
Thanks @ggmartins! Should be fixed. See commit.
