### ISSUE TITLE
netdisco error upon recovery from standby

### ISSUE THREAD

**Issue by crazyideas21** [noise-lab/iot-inspector-client#65]
Left IoT Inspector running for 3 hours. Accidentally put Windows 10 computer into standby mode. Recovered from standby mode and found the following error:

```
================================================================================
Time: 2020-04-26 23:08:19.895977
Function: <bound method NetdiscoWrapper._run_netdisco of <netdisco_wrapper.NetdiscoWrapper object at 0x000001F02CC7D5E0>> [] {}
Exception: [WinError 10055] An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full
Traceback (most recent call last):
  File "C:\Users\yuxingh\dev\iot-inspector-client\v2-src\utils.py", line 246, in safe_run
    return func(*args, **kwargs)
  File "C:\Users\yuxingh\dev\iot-inspector-client\v2-src\netdisco_wrapper.py", line 57, in _run_netdisco
    netdis.scan()
  File "C:\Users\yuxingh\dev\iot-inspector-client\v2-src\dev\lib\site-packages\netdisco\discovery.py", line 63, in scan
    self.gdm.scan()
  File "C:\Users\yuxingh\dev\iot-inspector-client\v2-src\dev\lib\site-packages\netdisco\gdm.py", line 23, in scan
    self.update()
  File "C:\Users\yuxingh\dev\iot-inspector-client\v2-src\dev\lib\site-packages\netdisco\gdm.py", line 80, in update
    sock.sendto(gdm_msg, (gdm_ip, gdm_port))
OSError: [WinError 10055] An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full




================================================================================
Time: 2020-04-26 23:08:20.991276
Function: <bound method ArpSpoof._arp_spoof of <arp_spoof.ArpSpoof object at 0x000001F02CC7DD90>> ('14:10:9f:e7:fe:02', '10.0.0.69', [('10.0.0.1', '8c:3b:ad:aa:a0:85'), ('10.0.0.3', 'a4:77:33:22:1a:4a'), ('10.0.0.31', '14:10:9f:e7:fe:02'), ('10.0.0.2', '68:c6:3a:bf:fc:77'), ('10.0.0.61', '74:f6:1c:08:86:b4'), ('10.0.0.17', 'd8:31:34:24:26:27'), ('10.0.0.14', '68:c6:3a:c2:1b:2e'), ('10.0.0.62', '14:10:9f:e7:fe:02'), ('10.0.0.63', '14:10:9f:e7:fe:02'), ('10.0.0.64', '14:10:9f:e7:fe:02'), ('10.0.0.65', '14:10:9f:e7:fe:02'), ('10.0.0.66', '14:10:9f:e7:fe:02'), ('10.0.0.67', '14:10:9f:e7:fe:02'), ('10.0.0.68', '14:10:9f:e7:fe:02'), ('10.0.0.69', '14:10:9f:e7:fe:02'), ('10.0.0.70', '14:10:9f:e7:fe:02'), ('10.0.0.71', '14:10:9f:e7:fe:02'), ('10.0.0.72', '14:10:9f:e7:fe:02'), ('10.0.0.73', '14:10:9f:e7:fe:02'), ('10.0.0.74', '14:10:9f:e7:fe:02'), ('10.0.0.75', '14:10:9f:e7:fe:02'), ('10.0.0.76', '14:10:9f:e7:fe:02'), ('10.0.0.77', '14:10:9f:e7:fe:02'), ('10.0.0.78', '14:10:9f:e7:fe:02'), ('10.0.0.79', '14:10:9f:e7:fe:02'), ('10.0.0.80', '14:10:9f:e7:fe:02')]) {}
Exception: exception: access violation reading 0x00000000000002A8
Traceback (most recent call last):
  File "C:\Users\yuxingh\dev\iot-inspector-client\v2-src\utils.py", line 246, in safe_run
    return func(*args, **kwargs)
  File "C:\Users\yuxingh\dev\iot-inspector-client\v2-src\arp_spoof.py", line 143, in _arp_spoof
    sc.send(dest_arp, verbose=0)
  File "C:\Users\yuxingh\dev\iot-inspector-client\v2-src\dev\lib\site-packages\scapy\sendrecv.py", line 316, in send
    socket = socket or conf.L3socket(*args, **kargs)
  File "C:\Users\yuxingh\dev\iot-inspector-client\v2-src\dev\lib\site-packages\scapy\arch\pcapdnet.py", line 316, in __init__
    self.ins = open_pcap(iface, MTU, self.promisc, 100,
  File "C:\Users\yuxingh\dev\iot-inspector-client\v2-src\dev\lib\site-packages\scapy\arch\windows\__init__.py", line 817, in open_pcap
    return _orig_open_pcap(iface_pcap_name, *args, **kargs)
  File "C:\Users\yuxingh\dev\iot-inspector-client\v2-src\dev\lib\site-packages\scapy\arch\pcapdnet.py", line 262, in <lambda>
    open_pcap = lambda *args, **kargs: _PcapWrapper_winpcap(*args, **kargs)
  File "C:\Users\yuxingh\dev\iot-inspector-client\v2-src\dev\lib\site-packages\scapy\arch\pcapdnet.py", line 217, in __init__
    pcap_setmintocopy(self.pcap, 0)
OSError: exception: access violation reading 0x00000000000002A8




================================================================================
Time: 2020-04-26 23:08:20.327278
Function: <bound method ArpScan._arp_scan_thread_helper of <arp_scan.ArpScan object at 0x000001F02CC7D310>> [] {}
Exception: exception: access violation reading 0x00000000000002A8
Traceback (most recent call last):
  File "C:\Users\yuxingh\dev\iot-inspector-client\v2-src\utils.py", line 246, in safe_run
    return func(*args, **kwargs)
  File "C:\Users\yuxingh\dev\iot-inspector-client\v2-src\arp_scan.py", line 78, in _arp_scan_thread_helper
    sc.sendp(arp_pkt, verbose=0)
  File "C:\Users\yuxingh\dev\iot-inspector-client\v2-src\dev\lib\site-packages\scapy\sendrecv.py", line 335, in sendp
    socket = socket or conf.L2socket(iface=iface, *args, **kargs)
  File "C:\Users\yuxingh\dev\iot-inspector-client\v2-src\dev\lib\site-packages\scapy\arch\pcapdnet.py", line 316, in __init__
    self.ins = open_pcap(iface, MTU, self.promisc, 100,
  File "C:\Users\yuxingh\dev\iot-inspector-client\v2-src\dev\lib\site-packages\scapy\arch\windows\__init__.py", line 817, in open_pcap
    return _orig_open_pcap(iface_pcap_name, *args, **kargs)
  File "C:\Users\yuxingh\dev\iot-inspector-client\v2-src\dev\lib\site-packages\scapy\arch\pcapdnet.py", line 262, in <lambda>
    open_pcap = lambda *args, **kargs: _PcapWrapper_winpcap(*args, **kargs)
  File "C:\Users\yuxingh\dev\iot-inspector-client\v2-src\dev\lib\site-packages\scapy\arch\pcapdnet.py", line 217, in __init__
    pcap_setmintocopy(self.pcap, 0)
OSError: exception: access violation reading 0x00000000000002A8




================================================================================
Time: 2020-04-26 23:08:22.400978
Function: <bound method SynScan._syn_scan_thread_helper of <syn_scan.SynScan object at 0x000001F02CC7D4C0>> [] {}
Exception: exception: access violation reading 0x00000000000002A8
Traceback (most recent call last):
  File "C:\Users\yuxingh\dev\iot-inspector-client\v2-src\utils.py", line 246, in safe_run
    return func(*args, **kwargs)
  File "C:\Users\yuxingh\dev\iot-inspector-client\v2-src\syn_scan.py", line 76, in _syn_scan_thread_helper
    sc.send(syn_pkt, verbose=0)
  File "C:\Users\yuxingh\dev\iot-inspector-client\v2-src\dev\lib\site-packages\scapy\sendrecv.py", line 316, in send
    socket = socket or conf.L3socket(*args, **kargs)
  File "C:\Users\yuxingh\dev\iot-inspector-client\v2-src\dev\lib\site-packages\scapy\arch\pcapdnet.py", line 316, in __init__
    self.ins = open_pcap(iface, MTU, self.promisc, 100,
  File "C:\Users\yuxingh\dev\iot-inspector-client\v2-src\dev\lib\site-packages\scapy\arch\windows\__init__.py", line 817, in open_pcap
    return _orig_open_pcap(iface_pcap_name, *args, **kargs)
  File "C:\Users\yuxingh\dev\iot-inspector-client\v2-src\dev\lib\site-packages\scapy\arch\pcapdnet.py", line 262, in <lambda>
    open_pcap = lambda *args, **kargs: _PcapWrapper_winpcap(*args, **kargs)
  File "C:\Users\yuxingh\dev\iot-inspector-client\v2-src\dev\lib\site-packages\scapy\arch\pcapdnet.py", line 217, in __init__
    pcap_setmintocopy(self.pcap, 0)
OSError: exception: access violation reading 0x00000000000002A8

```

**Comment by crazyideas21** [comment]
But the good news is that IoT Inspector for windows (after having local flask removed) had been running continuously for 3+ hours (from 19:20 till 23:08) without any apparent errors /cc: @kumarde 

Here's an overview of the traffic:

![image](https://user-images.githubusercontent.com/1479070/80330698-d951e300-8813-11ea-92fa-a177179a15da.png)

(Above: Note that the Chromecast has been playing a live video from YouTube.)

Below: macbook air in idle state:

![image](https://user-images.githubusercontent.com/1479070/80330814-3ea5d400-8814-11ea-8134-94112eaad9d1.png)
